// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WifiMap.Models;

namespace WifiMap.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class WifiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WifiMap.Models.Wifi", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<double>("GeoLat");

                    b.Property<double>("GeoLong");

                    b.Property<string>("SSID");

                    b.HasKey("Time");

                    b.ToTable("Wifies");
                });
#pragma warning restore 612, 618
        }
    }
}
